import { SchemaObject } from '@prisma-tools/schema'

export const schema: SchemaObject = {
  models: [
    {
      name: 'Page',
      fields: [
        {
          name: 'id',
          type: 'Int',
          isId: true,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'slug',
          type: 'String',
          isId: false,
          unique: true,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
      ],
      documentation: '',
    },
    {
      name: 'Address',
      fields: [
        {
          name: 'id',
          type: 'Int',
          isId: true,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'type',
          type: 'String',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'name',
          type: 'String',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'json',
          type: 'String',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'info',
          type: 'String',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'companyId',
          type: 'Int',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'company',
          type: 'Company',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'object',
          documentation: '',
        },
        {
          name: 'userId',
          type: 'String',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: true,
        },
        {
          name: 'user',
          type: 'User',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'object',
          documentation: '',
          relation: { fields: ['userId'], references: ['id'] },
        },
        {
          name: 'orders',
          type: 'Order',
          isId: false,
          unique: false,
          list: true,
          required: false,
          kind: 'object',
          documentation: '// @onDelete(SET_NULL)',
        },
      ],
      documentation: '',
    },
    {
      name: 'Role',
      fields: [
        {
          name: 'id',
          type: 'Int',
          isId: true,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'name',
          type: 'String',
          isId: false,
          unique: true,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'Staff',
          type: 'Staff',
          isId: false,
          unique: false,
          list: true,
          required: false,
          kind: 'object',
          documentation: '',
        },
        {
          name: 'schema',
          type: 'String',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
      ],
      documentation: '',
    },
    {
      name: 'Staff',
      fields: [
        {
          name: 'id',
          type: 'Int',
          isId: true,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'userId',
          type: 'String',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: true,
        },
        {
          name: 'user',
          type: 'User',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'object',
          documentation: '',
          relation: { fields: ['userId'], references: ['id'] },
        },
        {
          name: 'company',
          type: 'Company',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'object',
          documentation: '',
          relation: { fields: ['companyId'], references: ['id'] },
        },
        {
          name: 'companyId',
          type: 'Int',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: true,
        },
        {
          name: 'roleId',
          type: 'Int',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: true,
        },
        {
          name: 'role',
          type: 'Role',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'object',
          documentation: '',
          relation: { fields: ['roleId'], references: ['id'] },
        },
        {
          name: 'createdAt',
          type: 'DateTime',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'firstName',
          type: 'String',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'lastName',
          type: 'String',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'contact',
          type: 'Contact',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'object',
          documentation: '',
          relation: { fields: ['contactId'], references: ['id'] },
        },
        {
          name: 'contactId',
          type: 'Int',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: true,
        },
        {
          name: 'email',
          type: 'String',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
      ],
      documentation: '',
    },
    {
      name: 'Card',
      fields: [
        {
          name: 'id',
          type: 'Int',
          isId: true,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'type',
          type: 'String',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'cardType',
          type: 'String',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'name',
          type: 'String',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'lastFourDigit',
          type: 'Int',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'userId',
          type: 'String',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: true,
        },
        {
          name: 'user',
          type: 'User',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'object',
          documentation: '',
          relation: { fields: ['userId'], references: ['id'] },
        },
      ],
      documentation: '',
    },
    {
      name: 'Contact',
      fields: [
        {
          name: 'id',
          type: 'Int',
          isId: true,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'type',
          type: 'String',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'number',
          type: 'String',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'companyId',
          type: 'Int',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'company',
          type: 'Company',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'object',
          documentation: '',
        },
        {
          name: 'userId',
          type: 'String',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: true,
        },
        {
          name: 'user',
          type: 'User',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'object',
          documentation: '',
          relation: { fields: ['userId'], references: ['id'] },
        },
        {
          name: 'orders',
          type: 'Order',
          isId: false,
          unique: false,
          list: true,
          required: false,
          kind: 'object',
          documentation: '// @onDelete(SET_NULL)',
        },
        {
          name: 'staffs',
          type: 'Staff',
          isId: false,
          unique: false,
          list: true,
          required: false,
          kind: 'object',
          documentation: '// @onDelete(SET_NULL)',
        },
      ],
      documentation: '',
    },
    {
      name: 'Company',
      fields: [
        {
          name: 'id',
          type: 'Int',
          isId: true,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'slug',
          type: 'String',
          isId: false,
          unique: true,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'name',
          type: 'String',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'description',
          type: 'String',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'previewUrl',
          type: 'String',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'thumbnailUrl',
          type: 'String',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'platformSlug',
          type: 'String',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'address',
          type: 'Address',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'object',
          documentation: '',
          relation: { fields: ['addressId'], references: ['id'] },
        },
        {
          name: 'addressId',
          type: 'Int',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: true,
        },
        {
          name: 'contact',
          type: 'Contact',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'object',
          documentation: '',
          relation: { fields: ['contactId'], references: ['id'] },
        },
        {
          name: 'contactId',
          type: 'Int',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: true,
        },
        {
          name: 'platformId',
          type: 'Int',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: true,
        },
        {
          name: 'platform',
          type: 'Platform',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'object',
          documentation: '',
          relation: { fields: ['platformId'], references: ['id'] },
        },
        {
          name: 'products',
          type: 'Product',
          isId: false,
          unique: false,
          list: true,
          required: false,
          kind: 'object',
          documentation: '// @onDelete(CASCADE)',
        },
        {
          name: 'customers',
          type: 'Customer',
          isId: false,
          unique: false,
          list: true,
          required: false,
          kind: 'object',
          documentation: '// @onDelete(CASCADE)',
        },
        {
          name: 'orders',
          type: 'Order',
          isId: false,
          unique: false,
          list: true,
          required: false,
          kind: 'object',
          documentation: '// @onDelete(SET_NULL)',
        },
        {
          name: 'owner',
          type: 'User',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'object',
          documentation: '',
          relation: { fields: ['ownerId'], references: ['id'] },
        },
        {
          name: 'ownerId',
          type: 'String',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: true,
        },
        {
          name: 'invoices',
          type: 'Invoice',
          isId: false,
          unique: false,
          list: true,
          required: false,
          kind: 'object',
          documentation: '// @onDelete(SET_NULL)',
        },
        {
          name: 'reviews',
          type: 'Review',
          isId: false,
          unique: false,
          list: true,
          required: false,
          kind: 'object',
          documentation: '',
        },
        {
          name: 'staffs',
          type: 'Staff',
          isId: false,
          unique: false,
          list: true,
          required: false,
          kind: 'object',
          documentation: '',
        },
        {
          name: 'deliveryDetail',
          type: 'String',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'promotion',
          type: 'String',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'createdAt',
          type: 'DateTime',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'updatedAt',
          type: 'DateTime',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'categories',
          type: 'Category',
          isId: false,
          unique: false,
          list: true,
          required: false,
          kind: 'object',
          documentation: '',
          relation: { references: ['id'] },
        },
      ],
      documentation: '',
    },
    {
      name: 'Coupon',
      fields: [
        {
          name: 'id',
          type: 'Int',
          isId: true,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'name',
          type: 'String',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'code',
          type: 'String',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'image',
          type: 'String',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'discountInPercent',
          type: 'Int',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'numberOfCoupon',
          type: 'Int',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'numberOfUsedCoupon',
          type: 'Int',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
      ],
      documentation: '',
    },
    {
      name: 'Country',
      fields: [
        {
          name: 'id',
          type: 'Int',
          isId: true,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'code',
          type: 'Int',
          isId: false,
          unique: true,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'name',
          type: 'String',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'currency',
          type: 'String',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'platforms',
          type: 'Platform',
          isId: false,
          unique: false,
          list: true,
          required: false,
          kind: 'object',
          documentation: '// @onDelete(SET_NULL)',
        },
      ],
      documentation: '',
    },
    {
      name: 'Platform',
      fields: [
        {
          name: 'id',
          type: 'Int',
          isId: true,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'name',
          type: 'String',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'bannerImg',
          type: 'String',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'slug',
          type: 'String',
          isId: false,
          unique: true,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'ownerId',
          type: 'String',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: true,
        },
        {
          name: 'owner',
          type: 'User',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'object',
          documentation: '',
          relation: { fields: ['ownerId'], references: ['id'] },
        },
        {
          name: 'description',
          type: 'String',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'companies',
          type: 'Company',
          isId: false,
          unique: false,
          list: true,
          required: false,
          kind: 'object',
          documentation: '// @onDelete(SET_NULL)',
        },
        {
          name: 'categories',
          type: 'Category',
          isId: false,
          unique: false,
          list: true,
          required: false,
          kind: 'object',
          documentation: '// @onDelete(SET_NULL)',
        },
        {
          name: 'platformType',
          type: 'String',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'countryId',
          type: 'Int',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: true,
        },
        {
          name: 'country',
          type: 'Country',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'object',
          documentation: '',
          relation: { fields: ['countryId'], references: ['id'] },
        },
        {
          name: 'taxRate',
          type: 'Float',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'createdAt',
          type: 'DateTime',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
      ],
      documentation: '',
    },
    {
      name: 'User',
      fields: [
        {
          name: 'id',
          type: 'String',
          isId: true,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'createdAt',
          type: 'DateTime',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'email',
          type: 'String',
          isId: false,
          unique: true,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'firstName',
          type: 'String',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'lastName',
          type: 'String',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'token',
          type: 'String',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'googleId',
          type: 'String',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'walletId',
          type: 'String',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'password',
          type: 'String',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'income',
          type: 'Float',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'username',
          type: 'String',
          isId: false,
          unique: true,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'image',
          type: 'String',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'imagePublicId',
          type: 'String',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'coverImage',
          type: 'String',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'coverImagePublicId',
          type: 'String',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'isOnline',
          type: 'Boolean',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'companies',
          type: 'Company',
          isId: false,
          unique: false,
          list: true,
          required: false,
          kind: 'object',
          documentation: '// @onDelete(SET_NULL)',
        },
        {
          name: 'platforms',
          type: 'Platform',
          isId: false,
          unique: false,
          list: true,
          required: false,
          kind: 'object',
          documentation: '// @onDelete(SET_NULL)',
        },
        {
          name: 'addresses',
          type: 'Address',
          isId: false,
          unique: false,
          list: true,
          required: false,
          kind: 'object',
          documentation: '// @onDelete(SET_NULL)',
        },
        {
          name: 'cards',
          type: 'Card',
          isId: false,
          unique: false,
          list: true,
          required: false,
          kind: 'object',
          documentation: '// @onDelete(CASCADE)',
        },
        {
          name: 'contacts',
          type: 'Contact',
          isId: false,
          unique: false,
          list: true,
          required: false,
          kind: 'object',
          documentation: '// @onDelete(SET_NULL)',
        },
        {
          name: 'customers',
          type: 'Customer',
          isId: false,
          unique: false,
          list: true,
          required: false,
          kind: 'object',
          documentation: '// @onDelete(SET_NULL)',
        },
        {
          name: 'staffs',
          type: 'Staff',
          isId: false,
          unique: false,
          list: true,
          required: false,
          kind: 'object',
          documentation: '',
        },
      ],
      documentation: '',
    },
    {
      name: 'Customer',
      fields: [
        {
          name: 'id',
          type: 'Int',
          isId: true,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'firstName',
          type: 'String',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'lastName',
          type: 'String',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'email',
          type: 'String',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'address',
          type: 'String',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'zipcode',
          type: 'String',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'city',
          type: 'String',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'avatar',
          type: 'String',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'birthday',
          type: 'DateTime',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'firstSeen',
          type: 'DateTime',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'lastSeen',
          type: 'DateTime',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'hasOrdered',
          type: 'Boolean',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'latestPurchase',
          type: 'DateTime',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'hasNewsLetter',
          type: 'Boolean',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'groups',
          type: 'String',
          isId: false,
          unique: false,
          list: true,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'nbOrders',
          type: 'Int',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'reviews',
          type: 'Review',
          isId: false,
          unique: false,
          list: true,
          required: false,
          kind: 'object',
          documentation: '// @onDelete(CASACADE)',
        },
        {
          name: 'invoices',
          type: 'Invoice',
          isId: false,
          unique: false,
          list: true,
          required: false,
          kind: 'object',
          documentation: '// @onDelete(SET_NULL)',
        },
        {
          name: 'orders',
          type: 'Order',
          isId: false,
          unique: false,
          list: true,
          required: false,
          kind: 'object',
          documentation: '',
        },
        {
          name: 'company',
          type: 'Company',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'object',
          documentation: '',
          relation: { fields: ['companyId'], references: ['id'] },
        },
        {
          name: 'companyId',
          type: 'Int',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: true,
        },
        {
          name: 'userId',
          type: 'String',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: true,
        },
        {
          name: 'user',
          type: 'User',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'object',
          documentation: '',
          relation: { fields: ['userId'], references: ['id'] },
        },
        {
          name: 'image',
          type: 'String',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'totalOrder',
          type: 'Int',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'totalSpent',
          type: 'Float',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'createdAt',
          type: 'DateTime',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'private',
          type: 'Boolean',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
      ],
      documentation: '',
    },
    {
      name: 'Category',
      fields: [
        {
          name: 'id',
          type: 'Int',
          isId: true,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'name',
          type: 'String',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'products',
          type: 'Product',
          isId: false,
          unique: false,
          list: true,
          required: false,
          kind: 'object',
          documentation: '// @onDelete(SET_NULL)',
        },
        {
          name: 'platform',
          type: 'Platform',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'object',
          documentation: '',
          relation: { fields: ['platformId'], references: ['id'] },
        },
        {
          name: 'platformId',
          type: 'Int',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: true,
        },
        {
          name: 'slug',
          type: 'String',
          isId: false,
          unique: true,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'type',
          type: 'String',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'icon',
          type: 'String',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'parentId',
          type: 'Int',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: true,
        },
        {
          name: 'parent',
          type: 'Category',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'object',
          documentation: '',
          relation: {
            name: 'Children',
            fields: ['parentId'],
            references: ['id'],
          },
        },
        {
          name: 'children',
          type: 'Category',
          isId: false,
          unique: false,
          list: true,
          required: false,
          kind: 'object',
          documentation: '// @onDelete(SET_NULL)',
          relation: { name: 'Children' },
        },
        {
          name: 'companies',
          type: 'Company',
          isId: false,
          unique: false,
          list: true,
          required: false,
          kind: 'object',
          documentation: '',
        },
      ],
      documentation: '',
    },
    {
      name: 'Product',
      fields: [
        {
          name: 'id',
          type: 'Int',
          isId: true,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'width',
          type: 'Float',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'height',
          type: 'Float',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'price',
          type: 'Float',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'thumbnail',
          type: 'String',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'image',
          type: 'String',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'description',
          type: 'String',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'stock',
          type: 'Int',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'review',
          type: 'Review',
          isId: false,
          unique: false,
          list: true,
          required: false,
          kind: 'object',
          documentation: '// @onDelete(CASCADE)',
        },
        {
          name: 'orderItems',
          type: 'OrderItem',
          isId: false,
          unique: false,
          list: true,
          required: false,
          kind: 'object',
          documentation: '// @onDelete(SET_NULL)',
        },
        {
          name: 'company',
          type: 'Company',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'object',
          documentation: '',
          relation: { fields: ['companyId'], references: ['id'] },
        },
        {
          name: 'companyId',
          type: 'Int',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: true,
        },
        {
          name: 'sku',
          type: 'String',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'name',
          type: 'String',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'slug',
          type: 'String',
          isId: false,
          unique: true,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'salePrice',
          type: 'Float',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'discountInPercent',
          type: 'Int',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'type',
          type: 'String',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'gallery',
          type: 'String',
          isId: false,
          unique: false,
          list: true,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'categories',
          type: 'Category',
          isId: false,
          unique: false,
          list: true,
          required: false,
          kind: 'object',
          documentation: '// @onDelete(SET_NULL)',
        },
        {
          name: 'unit',
          type: 'String',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'createdAt',
          type: 'DateTime',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'published',
          type: 'Boolean',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
      ],
      documentation: '',
    },
    {
      name: 'OrderItem',
      fields: [
        {
          name: 'id',
          type: 'Int',
          isId: true,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'order',
          type: 'Order',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'object',
          documentation: '',
          relation: { fields: ['orderId'], references: ['id'] },
        },
        {
          name: 'orderId',
          type: 'Int',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: true,
        },
        {
          name: 'quantity',
          type: 'Int',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'name',
          type: 'String',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'weight',
          type: 'String',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'price',
          type: 'Float',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'productId',
          type: 'Int',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: true,
        },
        {
          name: 'product',
          type: 'Product',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'object',
          documentation: '',
          relation: { fields: ['productId'], references: ['id'] },
        },
        {
          name: 'image',
          type: 'String',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
      ],
      documentation: '',
    },
    {
      name: 'Order',
      fields: [
        {
          name: 'id',
          type: 'Int',
          isId: true,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'reference',
          type: 'String',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'customerId',
          type: 'Int',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: true,
        },
        {
          name: 'customer',
          type: 'Customer',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'object',
          documentation: '',
          relation: { fields: ['customerId'], references: ['id'] },
        },
        {
          name: 'subtotal',
          type: 'Float',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'deliveryFees',
          type: 'Float',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'taxRate',
          type: 'Float',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'taxes',
          type: 'Float',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'total',
          type: 'Float',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'status',
          type: 'String',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'returned',
          type: 'Boolean',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'invoice',
          type: 'Invoice',
          isId: false,
          unique: false,
          list: true,
          required: false,
          kind: 'object',
          documentation: '// @onDelete(SET_NULL)',
        },
        {
          name: 'reviews',
          type: 'Review',
          isId: false,
          unique: false,
          list: true,
          required: false,
          kind: 'object',
          documentation: '// @onDelete(SET_NULL)',
        },
        {
          name: 'orderItems',
          type: 'OrderItem',
          isId: false,
          unique: false,
          list: true,
          required: false,
          kind: 'object',
          documentation: '// @onDelete(SET_NULL)',
        },
        {
          name: 'company',
          type: 'Company',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'object',
          documentation: '',
          relation: { fields: ['companyId'], references: ['id'] },
        },
        {
          name: 'companyId',
          type: 'Int',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: true,
        },
        {
          name: 'deliveryTime',
          type: 'DateTime',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'createdAt',
          type: 'DateTime',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'paymentMethod',
          type: 'String',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'deliveryAdress',
          type: 'Address',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'object',
          documentation: '',
          relation: { fields: ['deliveryAddressId'], references: ['id'] },
        },
        {
          name: 'deliveryAddressId',
          type: 'Int',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: true,
        },
        {
          name: 'contact',
          type: 'Contact',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'object',
          documentation: '',
          relation: { fields: ['contactId'], references: ['id'] },
        },
        {
          name: 'contactId',
          type: 'Int',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: true,
        },
        {
          name: 'private',
          type: 'Boolean',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
      ],
      documentation: '',
    },
    {
      name: 'Invoice',
      fields: [
        {
          name: 'id',
          type: 'Int',
          isId: true,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'createdAt',
          type: 'DateTime',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'orderId',
          type: 'Int',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: true,
        },
        {
          name: 'order',
          type: 'Order',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'object',
          documentation: '',
          relation: { fields: ['orderId'], references: ['id'] },
        },
        {
          name: 'customerId',
          type: 'Int',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: true,
        },
        {
          name: 'customer',
          type: 'Customer',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'object',
          documentation: '',
          relation: { fields: ['customerId'], references: ['id'] },
        },
        {
          name: 'subtotal',
          type: 'Float',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'deliveryFees',
          type: 'Float',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'taxRate',
          type: 'Float',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'taxes',
          type: 'Float',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'total',
          type: 'Float',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'company',
          type: 'Company',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'object',
          documentation: '',
          relation: { fields: ['companyId'], references: ['id'] },
        },
        {
          name: 'companyId',
          type: 'Int',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: true,
        },
        {
          name: 'private',
          type: 'Boolean',
          isId: false,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
      ],
      documentation: '',
    },
    {
      name: 'Review',
      fields: [
        {
          name: 'id',
          type: 'Int',
          isId: true,
          unique: false,
          list: false,
          required: true,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'createdAt',
          type: 'DateTime',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'status',
          type: 'String',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'orderId',
          type: 'Int',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: true,
        },
        {
          name: 'order',
          type: 'Order',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'object',
          documentation: '',
          relation: { fields: ['orderId'], references: ['id'] },
        },
        {
          name: 'productId',
          type: 'Int',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: true,
        },
        {
          name: 'product',
          type: 'Product',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'object',
          documentation: '',
          relation: { fields: ['productId'], references: ['id'] },
        },
        {
          name: 'customerId',
          type: 'Int',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: true,
        },
        {
          name: 'customer',
          type: 'Customer',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'object',
          documentation: '',
          relation: { fields: ['customerId'], references: ['id'] },
        },
        {
          name: 'rating',
          type: 'Int',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'comment',
          type: 'String',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: false,
        },
        {
          name: 'company',
          type: 'Company',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'object',
          documentation: '',
          relation: { fields: ['companyId'], references: ['id'] },
        },
        {
          name: 'companyId',
          type: 'Int',
          isId: false,
          unique: false,
          list: false,
          required: false,
          kind: 'scalar',
          documentation: '',
          relationField: true,
        },
      ],
      documentation: '',
    },
  ],
  enums: [],
}
