export default () => [
  {
    firstName: 'James',
    lastName: 'Frank',
    contactNumber: '715-371-3507',
    email: 'jameslfrank@jourrapide.com',
    role: 'admin',
  },
  {
    firstName: 'Andre M.',
    lastName: 'Pollock',
    contactNumber: '937-667-7660',
    email: 'andreMPollock@jourrapide.com',
    role: 'admin',
  },
  {
    firstName: 'Debra J.',
    lastName: 'Nguyen',
    contactNumber: '508-588-8616',
    email: 'debraJNguyen@rhyta.com',
    role: 'manager',
  },
  {
    firstName: 'Erin E.',
    lastName: 'Gonzales',
    contactNumber: '989-981-9455',
    email: 'ErinEGonzales@teleworm.us',
    role: 'member',
  },
  {
    firstName: 'Carolyn B.',
    lastName: 'Coulter',
    contactNumber: '352-368-4009',
    email: 'carolynBCoulter@dayrep.com',
    role: 'member',
  },
  {
    firstName: 'Bryan G.',
    lastName: 'Hathaway',
    contactNumber: '215-645-0615',
    email: 'bryanGHathaway@jourrapide.com',
    role: 'delivery',
  },
  {
    firstName: 'Tony L.',
    lastName: 'Dematteo',
    contactNumber: '727-438-6098',
    email: 'tonyLDematteo@jourrapide.com',
    role: 'member',
  },
  {
    firstName: 'Leah M.',
    lastName: 'Cassella',
    contactNumber: '208-610-3130',
    email: 'leahMCassella@rhyta.com',
    role: 'admin',
  },
  {
    firstName: 'James C.',
    lastName: 'Chambers',
    contactNumber: '208-610-3130',
    email: 'jamesCChambers@teleworm.us',
    role: 'delivery',
  },
  {
    firstName: 'Mary R.',
    lastName: 'Wills',
    contactNumber: '901-268-7845',
    email: 'maryRWills@armyspy.com',
    role: 'admin',
  },
];
